let CONFIG = {
  TARGET_HEIGHT: 30,
  PERSON_WIDTH: 50,
  PERSON_HEIGHT: 30,
  PERSON_X_OFFSET: 100,
  PERSON_Y_OFFSET: 120,
  PERSON_LINK_X_OFFSET: 10,
  PERSON_VALUE_OFFSET: 15,
  ARROW_LENGTH: 20,
  COMPANY_X_OFFSET: 100,
  COMPANY_Y_OFFSET: 120,
  COMPANY_LINK_X_OFFSET: 10,
  COMPANY_VALUE_OFFSET: 15,
  COMPANY_WIDTH: 70,
  COMPANY_HEIGHT: 30,
  COMPANY_LINE_HEIGHT: 24,
  COMPANY_WORD_LEGNTH_PER_LINE: 7,
};

export default CONFIG;
